### ISSUE TITLE
Low memory not called

### ISSUE THREAD

**Issue by tajchert** [T-Spoon/Android-Developer-Toolbelt#1]
It doesn't trigger "Low Memory" on Nexus 7 2013 with Android 5.0.1 or Nexus 5 Android 5.1.0.
Shouldn't it trigger it? If not maybe it would be good to mark it in README.

**Comment by T-Spoon** [comment]
Hey,

Yeah actually the indicator is for the while system. On some devices this will never be triggered, but it should still produce the desired effects on your app once the free RAM counter goes down far enough. 

You're right though, this should he documented. 

Cheers.
